# Generated by Django 3.2.12 on 2022-03-09 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workershift',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='added_by',
            field=models.ForeignKey(blank=True, db_column='added_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workershift',
            index=models.Index(fields=['-created_at'], name='worker_shif_created_c83976_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shift_title'], name='shifts_shift_t_b7a0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['shift_session'], name='shifts_shift_s_9f39f0_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['-created_at'], name='shifts_created_1b152b_idx'),
        ),
    ]
